name: Python application

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  download:
    name: download artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Downland artifacts
        uses: actions/download-artifact@v3
        with:
          name: webapp
  packer:
    runs-on: ubuntu-latest
    needs: release
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./scripts/ami.pkr.hcl
      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: ./scripts/ami.pkr.hcl
          working_directory: ./
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
